export const draft = {
  "_2022": [
    "Abraham Lucas",
    "Ahmad Gardner",
    "Aidan Hutchinson",
    "Alec Pierce",
    "Amare Barno",
    "Andrew Booth Jr.",
    "Arnold Ebiketie",
    "Bernhard Raimann",
    "Boye Mafe",
    "Brandon Smith",
    "Breece Hall",
    "Calvin Austin III",
    "Cameron Jurgens",
    "Cameron Thomas",
    "Carson Strong",
    "Chad Muma",
    "Channing Tindall",
    "Charles Cross",
    "Chris Olave",
    "Christian Harris",
    "Christian Watson",
    "Coby Bryant",
    "Cole Strange",
    "Dai'Jean Dixon",
    "Damone Clark",
    "Daniel Faalele",
    "David Ojabo",
    "Daxton Hill",
    "DeAngelo Malone",
    "DeMarvin Leal",
    "Derek Stingley Jr.",
    "Desmond Ridder",
    "Devin Lloyd",
    "Devonte Wyatt",
    "Drake Jackson",
    "Drake London",
    "Dylan Parham",
    "Evan Neal",
    "Garrett Wilson",
    "George Karlaftis",
    "George Pickens",
    "Greg Dulcich",
    "Ikem Ekwonu",
    "Isaiah Likely",
    "Jahan Dotson",
    "Jalen Pitre",
    "Jalen Tolbert",
    "James Cook",
    "Jameson Williams",
    "Jaquan Brisker",
    "Jermaine Johnson II",
    "John Metchie III",
    "JoJo Domann",
    "Jordan Davis",
    "Josh Jobe",
    "Josh Paschal",
    "JT Woods",
    "Kaiir Elam",
    "Kayvon Thibodeaux",
    "Kellen Diesch",
    "Kenneth Walker III",
    "Kenny Pickett",
    "Kenyon Green",
    "Kerby Joseph",
    "Khalil Shakir",
    "Kingsley Enagbare",
    "Kyle Hamilton",
    "Kyler Gordon",
    "Leo Chenal",
    "Lewis Cine",
    "Logan Hall",
    "Luke Goedeke",
    "Malik Willis",
    "Matt Corral",
    "Myjai Sanders",
    "Nakobe Dean",
    "Nicholas Petit-Frere",
    "Nick Cross",
    "Nik Bonitto",
    "Perrion Winfrey",
    "Phidarian Mathis",
    "Quay Walker",
    "Roger McCreary",
    "Sam Howell",
    "Sean Rhyan",
    "Skyy Moore",
    "Tariq Woolen",
    "Travis Jones",
    "Travon Walker",
    "Trent McDuffie",
    "Trevor Penning",
    "Trey McBride",
    "Treylon Burks",
    "Troy Andersen",
    "Tyler Linderbaum",
    "Tyler Smith",
    "Velus Jones Jr.",
    "Wan'Dale Robinson",
    "Zion Johnson",
    "Zyon McCollum"
  ]
}